Update `elasticsible` with inventories

diff --git a/ansible/elasticsible b/ansible/elasticsible
--- a/ansible/elasticsible
+++ b/ansible/elasticsible
@@ -17,53 +17,89 @@ help () {
     fatal <<HELP_MSG
 Usage:
 
-    $0 [ -t sometag ] [ ... ]
+  $0 [ -t sometag ] [options]
+
+Environment options:
+  --test           Deploy to test environment.
+  --prod           Deploy to production environment.
+
+Common options:
+  --list-tags      List all available tags.
+
 HELP_MSG
 }
 
 ensure_suitcase () {
-  if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
-    curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
-      SUITCASE_DIR=$PWD/ansible-deps-cache \
-      SUITCASE_ANSIBLE_VERSION=9.3.0 \
-      SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
-      SUITCASE_WITH_KEYBASE=1 \
-      bash -x
-  fi
-  . ansible-deps-cache/lib.sh
-  ensure_ansible_runtime
+    if ! test -f ansible-deps-cache/.versions 2>/dev/null; then
+        curl https://raw.githubusercontent.com/epfl-si/ansible.suitcase/master/install.sh | \
+          SUITCASE_DIR=$PWD/ansible-deps-cache \
+          SUITCASE_ANSIBLE_VERSION=11.3.0 \
+          SUITCASE_ANSIBLE_REQUIREMENTS=requirements.yml \
+          SUITCASE_PIP_EXTRA="kubernetes" \
+          SUITCASE_WITH_KEYBASE=1 \
+          bash -x
+    fi
+    . ansible-deps-cache/lib.sh
+    ensure_ansible_runtime
+}
+
+ensure_login_oc () {
+    local cluster_url=$1
+
+    if ! oc whoami > /dev/null 2>&1 || ! oc whoami --show-server | grep -q "$cluster_url"; then
+        echo "Logging into OpenShift cluster at $cluster_url..."
+        if ! oc login "$cluster_url" --web; then
+            echo "Login failed. Exiting."
+            exit 1
+        fi
+    else
+        echo "Already logged into $cluster_url."
+    fi
+}
+
+switch_to_target_namespace () {
+    if ! oc project "$namespace" >/dev/null 2>&1; then
+        echo "Failed to switch to namespace '$namespace'."
+        exit 1
+    else
+        echo "Successfully switched to namespace '$namespace'."
+    fi
 }
 
 ensure_suitcase
-ensure_oc_login
 
 [ "$1" == "--help" ] && help
 
 declare -a ansible_args
 inventory_mode="test"
+cluster_url="https://api.ocpitst0001.xaas.epfl.ch:6443"
+namespace="svc0012t-search-engine"
 while [ "$#" -gt 0 ]; do
-  case "$1" in
-    --help)
-      help ;;
-    --prod)
-      inventory_mode="test-and-prod"
-      shift ;;
-    *)
-      ansible_args+=("$1")
-      shift ;;
-  esac
+    case "$1" in
+        --help)
+            help ;;
+        --test)
+            shift ;;
+        --prod)
+            inventory_mode="prod"
+            cluster_url="https://api.ocpitsp0001.xaas.epfl.ch:6443"
+            namespace="svc0012p-search-engine"
+            shift ;;
+        *)
+            ansible_args+=("$1")
+            shift ;;
+    esac
 done
 
-# https://github.com/ansible/ansible/issues/32499, https://bugs.python.org/issue35219
-case "$(uname -s)" in
-  Darwin) export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ;;
-esac
+ensure_login_oc "$cluster_url"
+switch_to_target_namespace
 
 inventories () {
-  case "$inventory_mode" in
-    test)          echo "-i inventory/test.yml" ;;
-    test-and-prod) echo "-i inventory/test.yml -i inventory/prod.yml" ;;
-  esac
+    case "$inventory_mode" in
+        test) echo "-i inventory/test.yml" ;;
+        prod) echo "-i inventory/prod.yml" ;;
+        *) fatal "Invalid inventory_mode" ;;
+    esac
 }
 
 ansible-playbook $(inventories) "${ansible_args[@]}" playbook.yml
